const villagers = {
    "Alex": {
        "Complete Breakfast": 5.0,
        "Salmon Dinner": 5.0,
        "Egg": 4.0,
        "Daffodil": 3.0,
        "Dandelion": 3.0,
        "Hazlenut": 3.0,
        "Leek": 3.0,
        "Snow Yam": 3.0,
        "Winter Root": 3.0,
        "Salmonberry": 2.0,
        "Wild Horseradish": 2.0,
        "Holly": 1.0,
        "Quartz": 1.0
    },
    "Elliott": {
        "Crab Cakes": 5.0,
        "Duck Feather": 5.0,
        "Lobster": 5.0,
        "Pomegranate": 5.0,
        "Tom Kha Soup": 5.0,
        "Octopus": 4.0,
        "Squid": 4.0,
        "Daffodil": 2.0,
        "Dandelion": 2.0,
        "Hazelnut": 2.0,
        "Holly": 2.0,
        "Leek": 2.0,
        "Pizza": 2.0,
        "Snow Yam": 2.0,
        "Wild Horseradish": 2.0,
        "Winter Root": 2.0
    },
    "Harvey": {
        "Coffee": 5.0,
        "Pickles": 5.0,
        "Super Meal": 5.0,
        "Truffle Oil": 5.0,
        "Wine": 5.0,
        "Daffodil": 4.0,
        "Dandelion": 4.0,
        "Duck Egg": 4.0,
        "Duck Feather": 4.0,
        "Goat Milk": 4.0,
        "Hazelnut": 4.0,
        "Holly": 4.0,
        "Large Goat Milk": 4.0,
        "Leek": 4.0,
        "Quartz": 4.0,
        "Snow Yam": 4.0,
        "Spring Onion": 4.0,
        "Wild Horseradish": 4.0,
        "Winter Root": 4.0,
        "Large Milk": 3.0,
        "Milk": 3.0,
        "Bread": 2.0,
        "Cheese": 2.0,
        "Goat Cheese": 2.0,
        "Coral": 1.0,
        "Nautilus Shell": 1.0,
        "Rainbow Shell": 1.0,
        "Salmonberry": 1.0,
        "Spice Berry": 1.0
    },
    "Sam": {
        "Cactus Fruit": 5.0,
        "Maple Bar": 5.0,
        "Pizza": 5.0,
        "Tigerseye": 5.0,
        "Joja Cola": 4.0,
        "Daffodil": 2.0,
        "Dandelion": 2.0,
        "Hazelnut": 2.0,
        "Holly": 2.0,
        "Leek": 2.0,
        "Quartz": 2.0,
        "Salmonberry": 2.0,
        "Seaweed": 2.0,
        "Snow Yam": 2.0,
        "Wild Horseradish": 2.0,
        "Winter Root": 2.0,
        "Coal": 1.0,
        "Copper Bar": 1.0,
        "Duck Mayonnaise": 1.0,
        "Gold Bar": 1.0,
        "Gold Ore": 1.0,
        "Iridium Bar": 1.0,
        "Iridium Ore": 1.0,
        "Iron Bar": 1.0,
        "Mayonnaise": 1.0,
        "Pickles": 1.0,
        "Refined Quartz": 1.0
    },
    "Sebastian": {
        "Frozen Tear": 5.0,
        "Obsidian": 5.0,
        "Pumpkin Soup": 5.0,
        "Sashimi": 5.0,
        "Void Egg": 5.0,
        "Quartz": 4.0,
        "Daffodil": 2.0,
        "Dandelion": 2.0,
        "Hazelnut": 2.0,
        "Holly": 2.0,
        "Leek": 2.0,
        "Salmonberry": 2.0,
        "Seaweed": 2.0,
        "Snow Yam": 2.0,
        "Wild Horseradish": 2.0,
        "Winter Root": 2.0,
        "Clay": 1.0,
        "Complete Breakfast": 1.0,
        "Farmer's Lunch": 1.0,
        "Omelet": 1.0
    },
    "Shane": {},
    "Abigail": {},
    "Emily": {},
    "Haley": {},
    "Leah": {},
    "Maru": {},
    "Penny": {},
    "Caroline": {},
    "Clint": {},
    "Demetrius": {},
    "Dwarf": {},
    "Evelyn": {},
    "George": {},
    "Gus": {},
    "Jas": {},
    "Jodi": {},
    "Kent": {},
    "Krobus": {},
    "Lewis": {},
    "Linus": {},
    "Marnie": {},
    "Pam": {},
    "Pierre": {},
    "Robin": {},
    "Sandy": {},
    "Vincent": {},
    "Willy": {},
    "Wizard": {}
};

module.exports = villagers;